# -*- coding: utf-8 -*-

import sys, math
from ddprintconstants import *

# genTempTable.py <e-steps-per-mm> <filament-diameter>

def genTempTable():

    baseTemp = 170.0
    baseFlowrate = 0.1;

    f = 2.5 # grad pro zusätzlichem mm³/s filament

    spm = int(sys.argv[1])
    aFilament = (math.pi * pow(float(sys.argv[2]), 2)) / 4.0

    print "// Generated by snippets/genTempTable.py"
    print "uint16_t tempExtrusionRateTable[NExtrusionLimit] = {"
    for i in range(NExtrusionLimit):

        t = baseTemp + i

        flowrate = baseFlowrate + i/f

        espeed = flowrate / aFilament
        # print "flowrate for temp %f: %f -> espeed %f" % (t, flowrate, espeed)

        steprate = espeed * spm
        tvs = 1.0/steprate
        timerValue = min(int(fTimer / steprate), 0xffff)

        print "    /* Temp: %f, max flowrate: %.1f mm³/s, max espeed: %.1f mm/s, steps/s: %d, steprate: %d us, timervalue: */ %d," % (t, flowrate, espeed, int(steprate), int(tvs*1000000), timerValue)

    print "};"

genTempTable()

