
ARDUINO_DIR  = /usr/share/arduino

TARGET       = firmware.fw

OBJDIR := build.fw

# Mega/Ramps board
BOARD_TAG    = mega
MCU = atmega2560
AVRDUDE_ARD_PROGRAMMER = wiring
# End Mega

ARDUINO_LIBS = SPI fw sdcard
USER_LIB_PATH = .

ARDUINO_PORT = /dev/ttyACM0

AVRDUDE = $(ARDUINO_DIR)/hardware/tools/avrdude
AVRDUDE_ARD_BAUDRATE = 115200
AVRDUDE_ARD_EXTRAOPTS = -D 

include ./Arduino.mk

# Mega/Ramps board
CPPFLAGS      +=  -DMOTHERBOARD=72 -I./fw
# End Mega

